# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: pcarleton's blog
description: > # this means to ignore newlines until "baseurl:"
  Thoughts on software by Paul Carleton
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: paulcarletonjr
github_username:  pcarleton

# Build settings
markdown: kramdown
